name: .github/workflows/semantic-release.yml

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['meerkat-core', 'meerkat-node', 'meerkat-browser']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run Semantic Release
        run: |
          cd ${{ matrix.package }}
          npm run release
